/* eslint-disable @typescript-eslint/no-base-to-string, no-control-regex -- XLSX escaping and filename sanitization accept arbitrary serializable values. */
import type { CgGridColumnDescriptor, CgGridExportResult } from './CgGrid.types';

const MIME = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' as const;
const encoder = new TextEncoder();
function xml(value: unknown): string { return String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;'); }
function crc32(bytes: Uint8Array): number { let crc = 0xffffffff; for (const byte of bytes) { crc ^= byte; for (let bit = 0; bit < 8; bit++) crc = crc >>> 1 ^ (crc & 1 ? 0xedb88320 : 0); } return (crc ^ 0xffffffff) >>> 0; }
function u16(value: number): Uint8Array { return Uint8Array.of(value & 255, value >>> 8 & 255); }
function u32(value: number): Uint8Array { return Uint8Array.of(value & 255, value >>> 8 & 255, value >>> 16 & 255, value >>> 24 & 255); }
function join(chunks: ReadonlyArray<Uint8Array>): Uint8Array { const size = chunks.reduce((sum, chunk) => sum + chunk.length, 0); const result = new Uint8Array(size); let offset = 0; for (const chunk of chunks) { result.set(chunk, offset); offset += chunk.length; } return result; }
function zip(entries: ReadonlyArray<{ name: string; data: string }>): Uint8Array {
  const locals: Uint8Array[] = []; const centrals: Uint8Array[] = []; let offset = 0;
  for (const entry of entries) { const name = encoder.encode(entry.name); const data = encoder.encode(entry.data); const crc = crc32(data); const local = join([u32(0x04034b50), u16(20), u16(0), u16(0), u16(0), u16(0), u32(crc), u32(data.length), u32(data.length), u16(name.length), u16(0), name, data]); locals.push(local); centrals.push(join([u32(0x02014b50), u16(20), u16(20), u16(0), u16(0), u16(0), u16(0), u32(crc), u32(data.length), u32(data.length), u16(name.length), u16(0), u16(0), u16(0), u16(0), u32(0), u32(offset), name])); offset += local.length; }
  const central = join(centrals); return join([...locals, central, u32(0x06054b50), u16(0), u16(0), u16(entries.length), u16(entries.length), u32(central.length), u32(offset), u16(0)]);
}
function excelDate(value: Date): number { return value.getTime() / 86400000 + 25569; }
function cell(reference: string, value: unknown, style?: number): string {
  const s = style === undefined ? '' : ` s="${style}"`; if (value === null || value === undefined) return `<c r="${reference}"${s}/>`;
  if (typeof value === 'number') return `<c r="${reference}"${s}><v>${value}</v></c>`; if (typeof value === 'boolean') return `<c r="${reference}" t="b"${s}><v>${value ? 1 : 0}</v></c>`; if (value instanceof Date) return `<c r="${reference}" s="${style ?? 1}"><v>${excelDate(value)}</v></c>`;
  return `<c r="${reference}" t="inlineStr"${s}><is><t xml:space="preserve">${xml(value)}</t></is></c>`;
}
function colName(index: number): string { let result = ''; for (let n = index + 1; n > 0; n = Math.floor((n - 1) / 26)) result = String.fromCharCode(65 + (n - 1) % 26) + result; return result; }
export function sanitizeGridExportFileName(value = 'grid-export.xlsx'): string { const base = value.trim().replace(/[<>:"/\\|?*\u0000-\u001f]/g, '_').replace(/[. ]+$/g, '') || 'grid-export'; const stem = base.replace(/\.xlsx$/i, '').replace(/[. ]+$/g, '') || 'grid-export'; return `${stem}.xlsx`.slice(0, 180); }
export function createGridXlsx<TItem>(items: ReadonlyArray<TItem>, columns: ReadonlyArray<CgGridColumnDescriptor<TItem>>, fileName?: string): CgGridExportResult {
  const exported = columns.filter((column) => column.visible !== false && column.exportEnabled !== false && column.accessor && !['selection', 'command', 'template'].includes(column.type));
  const rows = [[...exported.map((column, index) => cell(`${colName(index)}1`, column.title ?? column.fieldId))], ...items.map((item, row) => exported.map((column, index) => { const value = column.accessor?.(item); const native = column.type === 'date' && typeof value === 'string' ? new Date(value) : value; return cell(`${colName(index)}${row + 2}`, native, column.type === 'date' ? column.dateTime ? 2 : 1 : undefined); }))].map((cells, index) => `<row r="${index + 1}">${cells.join('')}</row>`).join('');
  const entries = [
    { name: '[Content_Types].xml', data: '<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>' },
    { name: '_rels/.rels', data: '<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>' },
    { name: 'xl/workbook.xml', data: '<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Data" sheetId="1" r:id="rId1"/></sheets></workbook>' },
    { name: 'xl/_rels/workbook.xml.rels', data: '<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>' },
    { name: 'xl/styles.xml', data: '<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="2"><numFmt numFmtId="164" formatCode="yyyy-mm-dd"/><numFmt numFmtId="165" formatCode="yyyy-mm-dd hh:mm"/></numFmts><fonts count="1"><font><sz val="11"/><name val="Calibri"/></font></fonts><fills count="1"><fill><patternFill patternType="none"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="3"><xf/><xf numFmtId="164" applyNumberFormat="1"/><xf numFmtId="165" applyNumberFormat="1"/></cellXfs></styleSheet>' },
    { name: 'xl/worksheets/sheet1.xml', data: `<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${rows}</sheetData></worksheet>` },
  ];
  return { fileName: sanitizeGridExportFileName(fileName), mimeType: MIME, bytes: zip(entries) };
}
export function downloadGridExport(result: CgGridExportResult): void { if (typeof document === 'undefined' || typeof URL === 'undefined' || typeof Blob === 'undefined') throw new Error('Browser downloading is unavailable in this environment.'); const url = URL.createObjectURL(new Blob([result.bytes as BlobPart], { type: result.mimeType })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = result.fileName; anchor.click(); URL.revokeObjectURL(url); }
